# name: code-qa

# on:
#   push:
#     branches: [main]
#   pull_request:
#     branches: [main]
#   workflow_dispatch:

# jobs:
#   setup:
#     name: Setup environment
#     runs-on: ubuntu-latest
#     outputs:
#       cache-key: ${{ steps.cache-key.outputs.cache_key }}

#     steps:
#       - uses: actions/checkout@v4

#       - uses: astral-sh/setup-uv@v5

#       - uses: actions/setup-python@v5
#         with:
#           python-version: 3.13

#       - name: Setup SSH keys
#         uses: webfactory/ssh-agent@v0.9.0
#         with:
#           ssh-private-key: |
#             ${{ secrets.G_ACTIONS_UTILS_KEY }}
#             ${{ secrets.G_ACTIONS_API_KEY }}
#             ${{ secrets.G_ACTIONS_PYTRADE_KEY }}

#       - id: cache-key
#         run: echo "cache_key=$(sha256sum uv.lock | cut -d ' ' -f1)" >> $GITHUB_OUTPUT

#       - name: Cache venv
#         uses: actions/cache@v4
#         id: cache
#         with:
#           path: .venv
#           key: venv-${{ steps.cache-key.outputs.cache_key }}

#       - name: Install dependencies if cache miss
#         if: steps.cache.outputs.cache-hit != 'true'
#         run: uv sync --locked --dev


#   lint:
#     needs: setup
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v4
#       - uses: astral-sh/setup-uv@v5
#       - uses: actions/setup-python@v5
#         with:
#           python-version: 3.13

#       - name: Reuse cached venv
#         uses: actions/cache@v4
#         with:
#           path: .venv
#           key: venv-${{ needs.setup.outputs.cache-key }}

#       - run: uv run ruff check
#       - run: uv run ruff format --check


#   type-check:
#     needs: setup
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v4
#       - uses: astral-sh/setup-uv@v5
#       - uses: actions/setup-python@v5
#         with:
#           python-version: 3.13

#       - name: Reuse cached venv
#         uses: actions/cache@v4
#         with:
#           path: .venv
#           key: venv-${{ needs.setup.outputs.cache-key }}

#       - run: uv run mypy .


#   test:
#     needs: setup
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v4
#       - uses: astral-sh/setup-uv@v5
#       - uses: actions/setup-python@v5
#         with:
#           python-version: 3.13

#       - name: Reuse cached venv
#         uses: actions/cache@v4
#         with:
#           path: .venv
#           key: venv-${{ needs.setup.outputs.cache-key }}

#       - run: uv run coverage run -m pytest
#       - run: uv run coverage report -m --skip-covered
